# Generated by Django 3.2.9 on 2022-02-04 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('GH', 'Gryffindor'), ('HH', 'Hufflepuff'), ('RH', 'Ravenclaw'), ('SH', 'Slytherin')], db_column='House', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Name', max_length=32)),
                ('surname', models.CharField(db_column='Surname', max_length=32)),
                ('gender', models.BooleanField(db_column='Gender', default=True)),
                ('age', models.IntegerField(db_column='Age', default=1)),
                ('photo', models.ImageField(db_column='Photo', upload_to='student_photos')),
                ('s_house', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='App.house')),
            ],
        ),
        migrations.CreateModel(
            name='Wand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Name', max_length=32)),
                ('w_student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='App.student')),
            ],
        ),
        migrations.CreateModel(
            name='MistakeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record', models.TextField(blank=True, db_column='Record', max_length=2000)),
                ('m_student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='App.student')),
            ],
        ),
        migrations.CreateModel(
            name='Magic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('N', 'Normal'), ('F', 'Forbidden')], db_column='Type', max_length=12)),
                ('name', models.CharField(db_column='Name', max_length=32)),
                ('m_wand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='App.wand')),
            ],
        ),
    ]
