# Generated by Django 3.2.9 on 2022-02-04 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magic',
            name='name',
            field=models.CharField(blank=True, db_column='Name', max_length=32),
        ),
        migrations.AlterField(
            model_name='magic',
            name='type',
            field=models.CharField(blank=True, choices=[('N', 'Normal'), ('F', 'Forbidden')], db_column='Type', max_length=12),
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(blank=True, db_column='Age', default=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.BooleanField(blank=True, db_column='Gender', default=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(blank=True, db_column='Name', max_length=32),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, db_column='Photo', upload_to='student_photos'),
        ),
        migrations.AlterField(
            model_name='student',
            name='surname',
            field=models.CharField(blank=True, db_column='Surname', max_length=32),
        ),
        migrations.AlterField(
            model_name='wand',
            name='name',
            field=models.CharField(blank=True, db_column='Name', max_length=32),
        ),
    ]
